config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  # get '/recipes', to: 'recipes#index'
  # new route needs to be above show - otherwise it is confused with :id
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # post '/recipes', to: 'recipes#create'
  # Replace all the above with "resources :recipes"
  resources :recipes do
    # Nested route here - comments are under recipes
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chefchats#show'
  resources :messages, only: [:create]
  get '/popular', to: 'recipes#popular'
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 140}
  belongs_to :chef
  belongs_to :recipe
  validates :chef_id, presence: true
  validates :recipe_id, presence: true
  # Ordered by updated date in descending order - ie. latest comments at the top
  default_scope -> { order(updated_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(comment_params)
    @comment.chef = current_chef
    if @comment.save
      ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
      # flash[:success] = "Comment submitted successfully"
      # redirect_to recipe_path(@recipe)
    else
      flash[:danger] = "Comment failed to submit! Please check you have entered a comment"
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    
    if @comment.chef == current_chef || current_chef.admin?
      @comment.destroy
      flash[:danger] = "Comment has been deleted!"
      redirect_to recipe_path(@comment.recipe)
    else
      flash[:danger] = "You are not authorised to delete this comment!"
      redirect_to root_path
    end
  end
  
  private
    def comment_params
      params.require(:comment).permit(:description)
    end
    
end

app/views/comments/_comment.html.erb
<div class="row comment-cable">
  <div class="col-md-2">
    <section class="chef_info center">
      <%= gravatar_for(comment.chef, size: 60) %>
    </section>
  </div>
  <div class="col-md-8 well">
    <p><%= comment.description %></p>
    <p>
      <span class="quiet"><small>Created: <%= time_ago_in_words(comment.created_at) %> ago by 
                                    <%= comment.chef.chefname.gsub(/\w{2,}\b/) { |word| word.capitalize } %></small></span>
    </p>
    <div class="recipe-actions">
      <% if logged_in? && (current_chef == comment.chef || current_chef.admin?) %>
        <%= link_to "Delete Comment", recipe_comment_path(comment.recipe, comment), method: :delete, 
                                        data: { confirm: "Are you sure you want to Delete this Comment?" }, 
                                        class: "btn btn-danger btn-xs" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="center">
  <%= will_paginate comments %>
</div>
<% comments.each do |comment| %>
  <%= render(partial: 'comments/comment', object: comment) %>
<% end %>
<div class="center">
  <%= will_paginate comments %>
</div>