config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  # get '/recipes', to: 'recipes#index'
  # new route needs to be above show - otherwise it is confused with :id
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # post '/recipes', to: 'recipes#create'
  # Replace all the above with "resources :recipes"
  resources :recipes do
    # Nested route here - comments are under recipes
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chefchats#show'
  resources :messages, only: [:create]
  get '/popular', to: 'recipes#popular'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum:5, maximum:500 }
  belongs_to :chef
  validates :chef_id, presence: true
  # Ordered by updated date in descending order - ie. latest recipes at the top
  default_scope -> { order(updated_at: :desc) }
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  # Destroy comments if destroying the recipe
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_current_recipe, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:index, :show, :popular]
  before_action :require_same_user_or_admin, only: [:edit, :update, :destroy]
  
  def index
    # Using the will_paginate gem for page pagination
    @recipes = Recipe.paginate(:page => params[:page], :per_page => 5)
  end
  
  def popular
    @myrecipes = Recipe.unscoped.all
                        .left_joins(:likes)
                        .group(:id)
                        .order('COUNT(likes.id) DESC')
    @recipes = @myrecipes.paginate(:page => params[:page], :per_page => 5)
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(:page => params[:page], :per_page => 5)
    @like = Like.new
    @likes = @recipe.likes
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    # Use the logged in chef
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe successfully created."
      # Go the recipe SHOW page
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Updated Recipe OK."
      # Go the recipe SHOW page
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end
  
  def destroy
    # Not sure if destroy can fail - not sure what to do?
    @recipe.destroy
    flash[:danger] = "Recipe: \"" + @recipe.name + "\" deleted"
    # Return to Index page
    redirect_to recipes_path
  end
  
  private
    def set_current_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    # white list the recipe parameters passed through to create action
    # here the syntax for many-to-many relationship with ingredients to expect a list of ingredient ids to 
    # be passed through is "ingredient_ids: []"
    def recipe_params
      params.require(:recipe).permit(:name,:description, ingredient_ids: [])
    end
    
    def require_same_user_or_admin
      if current_chef != @recipe.chef && !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes!"
        redirect_to recipes_path
      end
    end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', object: @recipe, error_message: fail_message %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, class: "form-control", rows: 10, placeholder: "Enter description and steps for recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |ing| %>
              <% ing.label(class: "checkbox-inline input-checkbox") {ing.check_box(class: "checkbox") + ing.text} %>
            <% end %>
          </div> 
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-red" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-offset-5 col-md-7 cancel">
      [ <%= link_to cancel_message, recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% object.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>
    <div class="col-md-8 well show-padding">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
         <span class="quiet"><small>Created By: <%= recipe.chef.chefname.gsub(/\w{2,}\b/) { |word| word.capitalize } + ", " + time_ago_in_words(recipe.created_at) + " ago" %>
                                                  | <%= pluralize(recipe.comments.count, 'Comment') %></small></span>
      </p>
      <div class="recipe-actions">
        <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
          <%= link_to "Edit Recipe", edit_recipe_path(recipe), class: "btn btn-warning btn-xs" %>
          <%= link_to "Delete Recipe", recipe_path(recipe), method: :delete, 
                                      data: { confirm: "Are you sure you want to Delete this Recipe?" }, 
                                      class: "btn btn-danger btn-xs" %>
        <% end %>
        
        <% if logged_in? && Like.find_by(recipe: recipe, chef: current_chef) == nil %>
          <%= link_to recipe_likes_path(recipe, Like.find_by(recipe: recipe, chef: current_chef)), :method => :post do %>
            <span class="like-box">
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <span class="like-count"><%= recipe.likes.count %></span>
            </span>
          <% end %>
        <% elsif logged_in? %>
          <%= link_to recipe_like_path(recipe, Like.find_by(recipe: recipe, chef: current_chef)), method: :delete do %>
            <span class="like-box">
              <i class="fa fa-heart" aria-hidden="true"></i>
              <span class="like-count"><%= recipe.likes.count %></span>
            </span>
          <% end %>
        <% else %>
          <span class="like-box">
            <% if recipe.likes.count > 0 %>
              <i class="fa fa-heart" aria-hidden="true"></i>
            <% else %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
            <% end %>
            <span class="like-count"><%= recipe.likes.count %></span>
          </span>
        <% end %>
  
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit a Recipe" %>
<%= render 'form', fail_message: "Failed to update", cancel_message: "CANCEL EDIT RECIPE" %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "ALL Recipes" %>
<div align="center">
  <%= will_paginate @recipes %>
</div>
<%= render 'recipe', object: @recipes %>
<div align="center">
  <%= will_paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a New Recipe" %>
<%= render 'form', fail_message: "Failed to create", cancel_message: "CANCEL NEW RECIPE" %>

app/views/recipes/popular.html.erb
<%= render 'shared/page_title', title: "Most Popular Recipes" %>
<div align="center">
  <%= will_paginate @recipes %>
</div>
<%= render 'recipe', object: @recipes %>
<div align="center">
  <%= will_paginate @recipes %>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2 show-padding">
  <h4 class="center description"><strong>Description and Steps: </strong></h4>
  <hr />
  <!-- By using simple_format it keeps the display of newlines if they were entered on creation -->
  <%= simple_format(@recipe.description) %>
  <hr />
  
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
    </p>
    <p class="center">
      <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    </p>
    <p class="center">
      <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <% if @recipe.ingredients.any? %>
    <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
      <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-warning btn-xs btn-margin" %>
      <%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete, 
                                      data: { confirm: "Are you sure you want to Delete this Recipe?" }, 
                                      class: "btn btn-danger btn-xs btn-margin" %>
    <% end %>
    <%= link_to "Return to Recipes List", recipes_path, class: "btn btn-primary btn-xs btn-margin" %>
    
  </div>
  <div class="show-like">
    <% if logged_in? && Like.find_by(recipe: @recipe, chef: current_chef) == nil %>
      <%= link_to recipe_likes_path(@recipe, Like.find_by(recipe: @recipe, chef: current_chef)), :method => :post do %>
        <span class="like-box keep-left">
          <i class="fa fa-heart-o" aria-hidden="true"></i>
          <span class="like-count"><%= @recipe.likes.count %></span>
        </span>
      <% end %>
    <% elsif logged_in? %>
      <%= link_to recipe_like_path(@recipe, Like.find_by(recipe: @recipe, chef: current_chef)), method: :delete do %>
        <span class="like-box keep-left">
          <i class="fa fa-heart" aria-hidden="true"></i>
          <span class="like-count"><%= @recipe.likes.count %></span>
        </span>
      <% end %>
    <% else %>
      <span class="like-box keep-left">
        <% if @recipe.likes.count > 0 %>
          <i class="fa fa-heart" aria-hidden="true"></i>
        <% else %>
          <i class="fa fa-heart-o" aria-hidden="true"></i>
        <% end %>
        <span class="like-count"><%= @recipe.likes.count %></span>
      </span>
    <% end %>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr/>
      <!-- Submit form via AJAX (rather than http) (via remote: true) so that form stays same -->
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-md-8">
            <%= f.text_area :description, class: "form-control", id: "form-comment", rows: 8, placeholder: "Enter your comment" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-red" %>
          </div>
        </div>
      <% end %>
      <hr/>
    </div>
  </div>
<% end %>

<% if @recipe.comments.count > 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Previous Comments:</h3>
      <!-- in javascript/comments.coffee file it is setup to prepend data here based on the comments id -->
      <div id="comments">
        <%= render(partial: 'comments/comments', object: @comments) %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3 class="comment-heading marg-bottom">No Previous Comments</h3>
      <div id="new-comments"></div>
    </div>
  </div>
<% end %>