config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  # get '/recipes', to: 'recipes#index'
  # new route needs to be above show - otherwise it is confused with :id
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # post '/recipes', to: 'recipes#create'
  # Replace all the above with "resources :recipes"
  resources :recipes do
    # Nested route here - comments are under recipes
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chefchats#show'
  resources :messages, only: [:create]
  get '/popular', to: 'recipes#popular'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :setup_ingredient, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]
  
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient created successfully"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient updated successfully"
      redirect_to @ingredient
    else
      render 'edit'
    end
  end

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end
  
  private
  
    def setup_ingredient
      @ingredient = Ingredient.find(params[:id])
    end
    
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
    
    def require_admin
      if !logged_in? || !current_chef.admin?
        flash[:danger] = "Only admin users can perform this action"
        redirect_to ingredients_path
      end
    end
end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', object: @ingredient, error_message: fail_message %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of ingredient", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-red" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-offset-5 col-md-7 cancel">
      [ <%= link_to cancel_message, ingredients_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge ingredient-actions"><%= link_to ingredient.name.gsub(/\w{2,}\b/) { |word| word.capitalize }, ingredient_path(ingredient) %></span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "Edit Ingredient" %>
<%= render 'form', fail_message: "Failed to modify", cancel_message: "CANCEL EDIT INGREDIENT" %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "All Available Ingredients" %>

<div align="center">
  <%= will_paginate %>
  <% @ingredients.each do |ingredient| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="chef-title"><%= link_to ingredient.name.gsub(/\w{2,}\b/) { |word| word.capitalize }, ingredient_path(ingredient) %></li>
          <li><small><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes %></small></li>
          <div class="chef-actions">
            <!-- Don't display the delete option for admin chefs -->
            <% if logged_in? && current_chef.admin? %>
              <li><%= link_to "Edit", edit_ingredient_path(ingredient), class: "btn btn-danger btn-xs" %></li>
            <% end %>
          </div>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Create a New Ingredient" %>
<%= render 'form', fail_message: "Failed to create", cancel_message: "CANCEL NEW INGREDIENT" %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: @ingredient.name.gsub(/\w{2,}\b/) { |word| word.capitalize} %>

<% if @ingredient_recipes.count > 0 %>
  <h4 align="center" class="marg-bottom">
    Recipe's containing <%= @ingredient.name.gsub(/\w{2,}\b/) { |word| word.capitalize } %>
  </h4>
  <div class="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
  <%= render 'recipes/recipe', object: @ingredient_recipes %>
  <div class="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
<% else %>
  <h4 align="center" class="marg-bottom">
    No recipes found for this ingredient
  </h4>
<% end %>