config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  # get '/recipes', to: 'recipes#index'
  # new route needs to be above show - otherwise it is confused with :id
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # post '/recipes', to: 'recipes#create'
  # Replace all the above with "resources :recipes"
  resources :recipes do
    # Nested route here - comments are under recipes
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chefchats#show'
  resources :messages, only: [:create]
  get '/popular', to: 'recipes#popular'
end

app/views/layouts/_footer.html.erb
<footer id="myFooter">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h5>Get started</h5>
                <ul>
                    <li>
                        <%= link_to_if(logged_in?, "Home", pages_home_path) do 
                                link_to("Home", root_path) 
                            end 
                        %>
                    </li>
                    <% if !logged_in? %>
                        <li><%= link_to "Sign up", signup_path %></li>
                        <li><%= link_to "Login", login_path %></li>
                    <% else %>
                        <li><%= link_to "Logout", logout_path, method: :delete %></li>
                    <% end %>
                </ul>
            </div>
            <div class="col-sm-4">
                <h5>About us</h5>
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">FAQS</a></li>
                </ul>
            </div>
            <div class="col-sm-4 info">
                <h5>Information</h5>
                <p> Written by <a href="https://craigeastwood.com">Craig Eastwood</a> as part of the Udemy Ruby on Rails course by Mashrur Hussain.</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <!-- Add the message as a bootstrap click to close message -->
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path, class: "menu-item" %></li>
        <li><%= link_to "All Recipes", recipes_path, class: "menu-item" %></li>
        <% if logged_in? %>
          <li><%= link_to "Chef Chat", chat_path, class: "menu-item" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle menu-item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create New Recipe", new_recipe_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Most Popular", popular_path %></li>
            </ul>
          </li>
        <% elsif %>
          <li><%= link_to "Most Popular", popular_path, class: "menu-item" %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle menu-item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Ingredients", ingredients_path %></li>
            <% if logged_in? && current_chef.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create New Ingredient", new_ingredient_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle menu-item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.gsub(/\w{2,}\b/) { |word| word.capitalize } %><%= " (Admin)" if current_chef.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit Profile", edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path, class: "menu-item" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <!-- Display temporary info messages for user with "flash" -->
    <%= render 'layouts/messages' %>
    
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>